### ISSUE TITLE
I get error, if you start on Windows

### ISSUE THREAD

**Issue by FranciscoReMo** [Luca1991/NDSFactory#1]
![image](https://user-images.githubusercontent.com/43990816/85599051-7088ba80-b64c-11ea-9e11-8e89e7a3c328.png)
![image](https://user-images.githubusercontent.com/43990816/85599113-80a09a00-b64c-11ea-9c9a-6baa50855ec2.png)

I research in the Net:
https://stackoverflow.com/questions/18138635/mingw-exe-requires-a-few-gcc-dlls-regardless-of-the-code
https://stackoverflow.com/questions/46728353/mingw-w64-whats-the-purpose-of-libgcc-s-seh-dll

I think the error has been the compiled.

**Comment by MacaronParisPretty** [comment]
I get the same error, running windows 10, 64 bit...

**Comment by Luca1991** [comment]
Sorry guys, I've been so busy lately..... 
Can you try building this yourself using the hints posted on the first stackoverflow link?
Please keep me updated!

Thanks,
Luca

**Comment by zefie** [comment]
From what I could find Googling, the missing DLLs are from MingW. I am assuming you compiled it with MingW-w64. The MingW license appears to allow you to share their binaries with your release. When you get some time you should be able to search your MingW folder for the DLLs and include them in the zip. I have not tried installing MingW and mixing DLLs because it likely will need the specific version you used (though I could be wrong).

**Comment by Luca1991** [comment]
@zefie thanks for the info. 

I think that i can try and fix this issue during this weekend (or on next monday).

Also, I dont't know, maybe it is better to switch to msvc for building the Windows version.

**Comment by Luca1991** [comment]
@FranciscoReMo @MacaronParisPretty @zefie 
I just updated the windows release. This time I used msvc2019. Please give it a try, and let me know if this issue is fixed.
Thanks a lot.

**Comment by MacaronParisPretty** [comment]
It now works for me <3 Thanks so much <3

**Comment by Luca1991** [comment]
@MacaronParisPretty Great! From now on I'll build using msvc2019 on windows.

I'm going to close this issue.
